### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by leg0** [leg0/mqtt-to-sqlite#1]
Configuration format: [toml](https://crates.io/crates/toml)

Options to configure:
- Path to CA root certificate
- Path to client certificate
- Path to client private key
- MQTT broker host name, broker port, ssl/tcp/ws
- Path to sqlite database
- Topics to subscribe to
- transformation from topic data to value (TBD)

```toml
[broker]
url = (tcp | ssl | ws)://hostname[:port]
mqtt_version = (3.1 | 3.1.1 | 5)

[broker.ssl]
ca_cert = /path/to/ca/root/cert.crt
client_cert = /path/to/client/cert    # required only if authentication with client cert
client_key = /path/to/client/key     # required only if authentication with client cert

[metrics]
  [metrics.<metric name1>]
  topic = <topic name>
  format = json # The only one for now
  value = some.thing.value # An expression to obtain the value from json object

  [metrics.<metric name2>]
  ...
```
